### ISSUE TITLE
Consulta e busca de registros médicos

### ISSUE THREAD

**Issue by papukweh** [lucianoacsilva/HealthLedger#1]
O usuário pode consultar registros médicos (informações a respeito de exames, cirurgias, consultas, prescrições) de um determinado paciente ou de todos eles;

## Tasks:
- [x] Modelar nossos dados seguindo fontes confiáveis (como o CFM)
- [x] Criar a aplicação front-end (React)
- [x] Criar a rota /records
- [x] Criar a rota /records/id
