### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by papukweh** [lucianoacsilva/HealthLedger#3]
Landing page com informações sobre o projeto a ser apresentado

## Tasks:
- [x] Criar a página no _github pages_
- [x] Popular a página com informações sobre o projeto
- [x] Formulário para conseguir e-mails de potenciais clientes
